version: "3"
services:
  NotificationDb:
    image: mongo:latest
    container_name: FUTA
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./database/mongodb/:/data/db
    ports:
      - "${MONGO_PORT}:27017"
